<?php

/**
 * Implements hook_schema_alter().
 */
function commerce_payment_transaction_revision_schema_alter(&$schema) {
  $schema['commerce_payment_transaction_revision']['fields']['order_id'] = array(
    'description' => 'The {commerce_order}.order_id of the order this payment is for.',
    'type' => 'int',
    'unsigned' => TRUE,
    'not null' => TRUE,
    'default' => 0,
  );
}

/**
 * Implements hook_install().
 */
function commerce_payment_transaction_revision_install() {
  $schema = array();
  commerce_payment_transaction_revision_schema_alter($schema);
  if (!db_field_exists('commerce_payment_transaction_revision', 'order_id')) {
    db_add_field('commerce_payment_transaction_revision', 'order_id', $schema['commerce_payment_transaction_revision']['fields']['order_id']);
    db_query('UPDATE {commerce_payment_transaction_revision} cptr JOIN {commerce_payment_transaction} cpt ON (cptr.transaction_id = cpt.transaction_id) SET cptr.order_id = cpt.order_id')->execute();
  }
}
